### ISSUE TITLE
Semantic version code generation

### ISSUE THREAD

**Issue by mtinnes** [AndreaBrighi/Gradle-Git-Sensitive-Semantic-Versioning-Plugin-for-Android#40]
I'm unable to switch the version code generation to semantic from incremental. I'm using the following gradle config:
```
    androidGitSemVer {
        minimumVersion.set("2.2.265")
        versionPrefix.set("v")
        incrementalCode.set(false) // Whether the version code should be use semantic versioning
    }
```

The version code generated is as follows, taken from the generated Android manifest:

```
    android:versionCode="104"
    android:versionName="2.2.265"
```

Something obvious I'm missing?

**Comment by AndreaBrighi** [comment]
To be honest I normally don't use the semantic versioning for the version code,
let me check the problem

**Comment by mtinnes** [comment]
Got it. This configuration seems to work for me. I also moved it higher up in the android section of the gradle file.

```
    androidGitSemVer {
        versionPrefix.set("v")
        incrementalCode.set(false) // Whether the version code should be use semantic versioning
        versionCodeMajorDigits.set(1) // How many digits for the major version (default 3)
        versionCodeMinorDigits.set(3) // How many digits for the minor version (default 3)
        versionCodePatchDigits.set(3) // How many digits for the patch version (default 3)
        assignGitSemanticVersion()
    }
```

**Comment by AndreaBrighi** [comment]
Great!
Thanks for sharing your configuration so if anyone else should have a similar problem they already have a solution.
Mean while il try to figurate out why your previous configuration didn't work (it seems fine to me)

**Comment by AndreaBrighi** [comment]
Can I ask you how you find this plugin?
It was a university project and I thought I was the only one using it

**Comment by mtinnes** [comment]
just searching for semver gradle plugins - I think it was listed on a maven
repository site.

**Comment by AndreaBrighi** [comment]
ok thank for using it, I try to keep it update.
Anyway I tested your first configuration and it worked on the unit test

```
"test issues #40 case" {
            val project = configuredPlugin(
                """
                minimumVersion.set("2.2.265")
                versionPrefix.set("v")
                incrementalCode.set(false)
                """.trimIndent(),
            ) {
                initGit()
            }
            val result = project.runGradle()
            println(result)
            result shouldContain "2.2.265"
            val resultCode = project.runGradleCode()
            println(resultCode)
            resultCode shouldContain "2002265"
```

**Comment by mtinnes** [comment]
ok, well maybe it was the placement within the gradle file. I moved higher
up in the file.

**Comment by AndreaBrighi** [comment]
ok, I'm going to close the issues so

**Comment by mtinnes** [comment]
Hi Andrea, can you help me understand the correct tagging for development => release? for example, if I am starting development on a new version (ie. v2.2.266), when would I add that tag? I would like dev builds to utilize this new version in the naming, however this prevents a 'release' build using this version since there would be commits after the tag was created.

**Comment by AndreaBrighi** [comment]
If I understand correctly your current version is 2.2.265 and you want to release 2.2.266, am I right?
I presume there aren't any previous tag in your repository.

**Comment by mtinnes** [comment]
Right, however I'd like to develop on the 2.2.266 version prior to release
but it seems as though you cannot have any commits prior to the 2.2.266 tag
in order to have a clean 'release' build.
Ideally there would be a number of 2.2.266 dev build prior to the final
release, something like:

2.2.266-dev01+354b44a.apk
2.2.266-dev02+354b44b.apk
2.2.266-dev03+354b44c.apk
-----
2.2.266.apk

**Comment by AndreaBrighi** [comment]
I' m sorry but the basic plugin was not designed for such a scenario, so neither is this one.
When you commit, the plugin automatically thinks it's a new release.

**Comment by AndreaBrighi** [comment]
I have to try, but I'm quite certain that it is not possible.
However, it's possible that the version between the release could be named 2.2.265-dev* if there isn't a tag on the first commit.
This is because until release, the plugin is not certain of the version, which can be 2.2.266 or 2.3.0 or 3.0.0 based on the semantic release concept

**Comment by AndreaBrighi** [comment]
I understand what you mean, it's a bug of the plugin I use as base, there is a similar issue:
[https://github.com/DanySK/git-sensitive-semantic-versioning-gradle-plugin/issues/595](https://github.com/DanySK/git-sensitive-semantic-versioning-gradle-plugin/issues/595)
It's the same problem, right?

**Comment by AndreaBrighi** [comment]
The new version fixes the problem.
Currently, there isn't a conventional commit implementation, but the version is increased by one patch
